"use client";

import StyledComponentsRegistry from "@/lib/registry";
import { CssBaseline } from "@mui/material";
import { GlobalStyle } from "@/style/GlobalStyle";
import { Cabin } from "next/font/google";
import { usePathname } from "next/navigation";
import { checkPublicRoute } from "@/utils/checkPublicRoute";
import PrivateRoute from "@/components/PrivateRoute";
import * as S from "./style";
import { UserAuthenticationProvider } from "@/contexts/UserAuthContext";
import NavBar from "@/components/NavBar";
import { ProductsInfoProvider } from "@/contexts/ProductsInfoContext";

const cabin = Cabin({ subsets: ["latin"] });

export const metadata = {
  title: "Compra aí na moral",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathName = usePathname();
  const isPublicRoute = checkPublicRoute(pathName!);

  return (
    <html lang="pt-BR">
      <CssBaseline />
      <GlobalStyle />
      <StyledComponentsRegistry>
        <UserAuthenticationProvider>
          <ProductsInfoProvider>
            <body className={cabin.className}>
              <NavBar />
              <S.MainTag>
                {isPublicRoute && children}
                {!isPublicRoute && <PrivateRoute>{children}</PrivateRoute>}
              </S.MainTag>
            </body>
          </ProductsInfoProvider>
        </UserAuthenticationProvider>
      </StyledComponentsRegistry>
    </html>
  );
}
